# Generated by Django 5.2.4 on 2025-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles/'),
        ),
    ]
