# Generated by Django 5.2.4 on 2025-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('domaine', models.CharField(max_length=40)),
                ('profile', models.ImageField(default='profiles/profile.png', upload_to='profiles/')),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('ami', models.ManyToManyField(blank=True, to='users.utilisateur')),
            ],
        ),
    ]
