# Generated by Django 5.2.4 on 2025-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile',
            field=models.ImageField(default='media/profiles/profile.png', upload_to='media/profiles/'),
        ),
    ]
