# Generated by Django 5.2.4 on 2025-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='contenu',
            field=models.TextField(max_length=5000),
        ),
    ]
